# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#
# mkdocs.yml
#
# MkDocs configuration file.
#
# Copyright 2024 Nervosys, LLC
#

site_name: "AutonomySim"
site_description: "The simulation engine for autonomous systems"
site_url: "https://github.com/nervosys/AutonomySim"
site_dir: "build_docs"

repo_name: "nervosys/AutonomySim"
repo_url: "https://github.com/nervosys/AutonomySim"
remote_branch: "gh-pages"
remote_name: "origin"
edit_uri: "edit/master/docs/"

copyright: "Copyright &copy; 2024 <a href=https://nervosys.ai/>Nervosys, LLC</a>"

theme:
        name: material # options: readthedocs mkdocs material
        features:
                - announce.dismiss
                - content.code.annotate
                - content.code.copy
                - content.tabs.link
                # - header.autohide
                # - mkdocstrings
                # - navigation.expand
                # - navigation.instant
                - navigation.top
                # - navigation.tabs
                # - navigation.sections
                # - navigation.instant
                - navigation.path
                - navigation.footer
                # - navigation.tracking
                # - search.highlight
                - search.suggest
                - search.share
                - toc.follow
                - toc.integrate
        font:
                text: "Roboto"
                code: "Roboto Mono"
        language: en
        palette:
                - media: "(prefers-color-scheme)"
                  toggle:
                          icon: material/brightness-auto
                          name: "Switch to light mode"
                - media: "(prefers-color-scheme: light)"
                  scheme: nervosys_light
                  toggle:
                          icon: material/brightness-7
                          name: "Switch to dark mode"
                - media: "(prefers-color-scheme: dark)"
                  scheme: nervosys_dark
                  toggle:
                          icon: material/brightness-4
                          name: "Switch to system preference"
        favicon: media/images/rune.svg
        icon:
                logo: material/book-open-page-variant
                repo: fontawesome/brands/git-alt
                edit: material/pencil
                view: material/eye

plugins:
        - search
        - offline
        #- social
        #- optimize

markdown_extensions:
        - admonition
        - toc:
                  permalink: "#"
        - attr_list
        - md_in_html
        - pymdownx.highlight:
                  use_pygments: false
                  # pygments_style: default
                  # pygments_lang_class: true
                  anchor_linenums: true
                  line_spans: __span
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.superfences
        - pymdownx.arithmatex:
                  generic: true

extra_css:
        - css/extra.css
        - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css" # highlight.js

extra_javascript:
        - js/extra.js
        - js/mathjax.js
        - "https://polyfill.io/v3/polyfill.min.js?features=es6"
        - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js" # highlight.js

extra:
        highlightjs: true
        version:
                default: latest
        feature:
                tabs: true
        analytics:
                provider: google
                property: "G-QQF2PS4P1M"
        social:
                - icon: fontawesome/brands/github-alt
                  link: "https://github.com/nervosys/AutonomySim"
                - icon: fontawesome/brands/discord
                  link: "https://discord.gg/x84JXYje"
                - icon: fontawesome/brands/x-twitter
                  link: "https://x.com/nervosys"
        generator: false

validation:
        omitted_files: warn
        absolute_links: warn
        unrecognized_links: warn

nav:
        - index.md # generated with MkDocs
        - CHANGELOG.md
        - "API Documentation":
                  - "Python API": api/python/html/index.html # generated with Sphinx
                  - "C++ API": api/cpp/html/index.html # generated with Doxygen, Breathe, Sphinx
        - "Building AutonomySim":
                  - project_binaries.md
                  - build_windows.md
                  - build_linux.md
                  - build_macos.md
                  - docker_ubuntu.md
                  - azure.md
                  - unreal_envs.md
                  - build_faq.md
        - "Using AutonomySim":
                  - apis.md
                  - apis_image.md
                  - apis_cpp.md
                  - development_workflow.md
                  - settings.md
                  - camera_views.md
                  - using_car.md
                  - controller_robot.md
                  - controller_remote.md
                  - controller_wired.md
                  - controlller_wheel.md
                  - multivehicle.md
                  - "Sensors":
                            - sensors.md
                            - lidar.md
                            - distance_sensor.md
                            - InfraredCamera.md
                  - "ROS":
                            - ros_pkgs.md
                            - ros_pkgs_tutorial.md
                  - gazebo_drone.md
                  - retexturing.md
                  - meshes.md
                  - playback.md
                  - voxel_grid.md
                  - event_sim.md
        - "Design":
                  - design.md
                  - project_structure.md
                  - apis_new.md
                  - Modifying Recordin data_capture.md
                  - coding_guidelines.md
                  - robot_controller.md
                  - simple_flight.md
                  - hello_drone.md
        - "Flight Controllers":
                  - "Pixhawk/PX4":
                            - px4_setup.md
                            - px4_sitl.md
                            - px4_sitl_wsl2.md
                            - px4_lockstep.md
                            - px4_multivehicle.md
                            - "AutonomySim with Pixhawk": "https://youtu.be/1oY8Qu5maQQ"
                            - "PX4 Setup with AutonomySim": "https://youtu.be/HNWdYrtw3f0"
                            - "Debugging Attitude Estimation": "https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be"
                            - "Intercepting MavLink Messages": "https://github.com/nervosys/AutonomySim/wiki/Intercepting-MavLink-messages"
                            - "Rapid Descent on PX4 Drones": "https://github.com/nervosys/AutonomySim/wiki/Rapid-Descent-on-PX4-drones"
                            - px4_build.md
                            - px4_logging.md
                            - mavlink_logviewer.md
                            - mavlink_playback.md
                            - mavlink_comm.md
                            - mavlink_mocap.md
                  - "APM/ArduPilot":
                            - "ArduPilot SITL Setup": "https://ardupilot.org/dev/docs/building-the-code.html"
                            - "AutonomySim & ArduPilot": "https://ardupilot.org/dev/docs/sitl-with-AirSim.html"
        - "Upgrading":
                  - unreal_upgrading.md
                  - apis_upgrading.md
                  - settings_upgrading.md
        - "Community Tutorials":
                  - reinforcement_learning.md
                  - "Using Environments from Marketplace": "https://www.youtube.com/watch?v=y09VbdQWvQY"
                  - "Simple Collision Avoidance": "https://github.com/simondlevy/AirSimTensorFlow"
                  - "Autonomous Driving on Azure": "https://aka.ms/AutonomousDrivingCookbook"
                  - "Building Hexacopter": "https://github.com/nervosys/AutonomySim/wiki/hexacopter"
                  - "Moving on Path Demo": "https://github.com/nervosys/AutonomySim/wiki/moveOnPath-demo"
                  #- Building Point Clouds: point_clouds.md
                  - surveying.md
                  - orbit.md
                  - "Importing a custom multirotor mesh": "https://youtu.be/Bp86WiLUC80"
                  - object_detection.md
                  - "AutonomySim with MAVROS and PX4": "https://youtu.be/ZonkdMcwXH4"
        - "Other":
                  - real_vhicles.md
                  - cmake_linux.md
                  - performance_hardware.md
                  - format_pfm.md
                  - unreal_projects.md
                  - unreal_blocks.md
                  - unreal_plugins.md
                  - "Formula Student Technion Self-driving Car": "https://github.com/nervosys/AutonomySim/wiki/technion"
        - userbase.md
        - "Support":
                  - faq.md
                  - SUPPORT.md
                  - create_issues.md
                  - CONTRIBUTING.md
