ARG BASE_IMAGE=nvidia/cudagl:11.4.0-devel
FROM $BASE_IMAGE

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils

RUN python3 -m pip install --upgrade pip && \
	pip3 install setuptools wheel && \
	pip3 install autonomysim

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash autonomysim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser autonomysim_user sudo && \
	adduser autonomysim_user audio && \
	adduser autonomysim_user video

USER autonomysim_user
WORKDIR /home/autonomysim_user

RUN mkdir -p /home/autonomysim_user/Documents/AutonomySim
COPY settings.json /home/autonomysim_user/Documents/AutonomySim
#ADD Documents /home/autonomysim_user/Documents

RUN sudo chown -R autonomysim_user /home/autonomysim_user
