ARG BASE_IMAGE=nvidia/cudagl:11.4.0-devel
FROM $BASE_IMAGE

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils

RUN python3 -m pip install --upgrade pip && \
    pip3 install setuptools wheel && \
    pip3 install AutonomySim

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash AutonomySim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser AutonomySim_user sudo && \
	adduser AutonomySim_user audio && \
	adduser AutonomySim_user video

USER AutonomySim_user
WORKDIR /home/AutonomySim_user

RUN mkdir -p /home/AutonomySim_user/Documents/AutonomySim
COPY settings.json /home/AutonomySim_user/Documents/AutonomySim
#ADD Documents /home/AutonomySim_user/Documents

RUN sudo chown -R AutonomySim_user /home/AutonomySim_user
