---
#----------------------------------------------------------------------------------------
# FILENAME:
#   test_macos.yml
# DESCRIPTION:
#   GitHub Actions configuration for macOS.
# AUTHOR:
#   Adam Erickson (Nervosys)
# DATE:
#   2024-02-20
# NOTES:
#   - Homebrew is installed by default.
#
#   Copyright © 2024 Nervosys, LLC
#----------------------------------------------------------------------------------------

name: "Build: macOS"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]
  # workflow_dispatch:

jobs:
  build-macos:
    runs-on: ${{ matrix.os }} # macos-latest
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14] # versions: [11: Big Sur, 12: Monterey, 13: Ventura, 14: Sonoma]
        # arch:
        #   - amd64
        #   - arm64
    steps:
      - uses: actions/checkout@v4

      - name: "Update Homebrew and Install Azure CLI"
        shell: bash
        run: |
          brew unlink python@3.12 && brew link --overwrite python@3.12
          brew unlink python@3.11 && brew link --overwrite python@3.11
          brew unlink python@3.10 && brew link --overwrite python@3.10
          brew update && brew upgrade
          brew install azure-cli

      - name: "Install AutonomySim Dependencies"
        shell: bash
        run: bash ./scripts/setup.sh

      - name: "Build AutonomySim"
        shell: bash
        run: bash ./scripts/build.sh

      # - name: "Build AutonomySim ROS2 Wrapper"
      #   shell: bash
      #   run: bash ./scripts/build_ros2_macos.sh
