---
#----------------------------------------------------------------------------------------
# FILENAME:
#   test_windows.yml
# DESCRIPTION:
#   GitHub Actions configuration for Windows.
# AUTHOR:
#   Adam Erickson (Nervosys)
# DATE:
#   2024-02-20
# NOTES:
#   - Requires Visual Studio 2022 Build Tools v143 (windows-2022)?
#
#   Copyright © 2024 Nervosys, LLC
#----------------------------------------------------------------------------------------

name: "Build: Windows"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]
  # workflow_dispatch:

jobs:
  build-windows-cmd:
    runs-on: ${{ matrix.os }} # windows-latest
    strategy:
      matrix:
        os: [windows-2022] # versions: [2019: 10, 2022: 11]
        arch:
          - amd64
          # - arm64
    steps:
      - uses: actions/checkout@v4
      #
      # - name: "Enable Developer Command Prompt for Visual Studio"
      #   uses: ilammy/msvc-dev-cmd@v1
      #
      # - name: "Add MSBuild to PATH"
      #   uses: microsoft/setup-msbuild@v2
      #
      # REM Initialize Visual Studio 2022 Developer Command Prompt and prepend MSBuild to PATH.
      # REM setx PATH "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\;%PATH%"
      # REM set CMAKE_GENERATOR_PLATFORM = "Visual Studio 17 2022"
      #
      - name: "Build AutonomyLib"
        if: ${{ matrix.os == 'windows-2022' }}
        shell: cmd
        run: |
          set WorkingDir=%cd%
          echo "Current directory: %WorkingDir%"
          cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\LaunchDevCmd.bat"
          cd %WorkingDir%
          scripts\cmd\build.cmd

  build-windows-pwsh:
    runs-on: ${{ matrix.os }} # windows-latest
    strategy:
      matrix:
        os: [windows-2022] # versions: [2019: 10, 2022: 11]
        arch:
          - amd64
          # - arm64
    steps:
      - uses: actions/checkout@v4
      #
      # - name: "Add MSBuild to PATH"
      #   uses: microsoft/setup-msbuild@v2
      #
      - name: "Build AutonomyLib"
        if: ${{ matrix.os == 'windows-2022' }}
        shell: pwsh
        run: |
          # Initialize Visual Studio 2022 Developer Command Prompt and prepend MSBuild to PATH.
          [String]$WorkingDir = $PWD.Path
          Write-Output "Current directory: $WorkingDir"
          . 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1' -Latest
          Set-Location "$WorkingDir"
          # $ENV:Path += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin"
          # $CMAKE_GENERATOR_PLATFORM = 'Visual Studio 17 2022'
          Set-PSDebug -Trace 1
          .\scripts\build.ps1 -BuildMode 'Release' -Automate
