name: "Build: Windows"

on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ${{ matrix.os }} # windows-latest
    strategy:
      matrix:
        os: [windows-2019, windows-2022] # versions: [2019: 10, 2022: 11]
        arch:
          - amd64
          # - arm64

    # sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: "Enable Developer Command Prompt"
        uses: ilammy/msvc-dev-cmd@v1

      - name: "Build AutonomySim"
        shell: pwsh
        run: ./scripts/build.ps1
