name: "Documentation Build and Deployment"

on: [push, pull_request, workflow_dispatch] # triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: "Install dependencies: MkDocs Material, Sphinx Immaterial"
        shell: bash
        run: |
          python3 -m venv .env  # virtual environment to avoid dependecy issues
          source ./.env/bin/activate
          python3 -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions mkdocstrings[python]
          pip install sphinx sphinx-immaterial darkdetect numpy msgpack-rpc-python

      - name: "Build API documentation: Sphinx Immaterial"
        shell: bash
        run: |
          source ./.env/bin/activate
          (cd ./python/docs; make html)
          cp -r ./python/docs/_build ./docs/api_docs/  # copy generated API documentation
          deactivate

      - name: "Build main documentation: MkDocs Material"
        shell: bash
        #run: bash ./scripts/build_docs.sh
        run: |
          cp ./README.md ./docs/
          sed -i 's/](docs\//](/g' ./docs/README.md
          source ./.env/bin/activate
          mkdocs build
          deactivate

      # Only on commits to 'master' branch
      - name: "Deploy master branch"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_docs
