name: "Build: macOS"

on: [push, pull_request, workflow_dispatch] # triggers

jobs:
  build-macos:
    runs-on: ${{ matrix.os }} # macos-latest
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14] # versions: [11: Big Sur, 12: Monterey, 13: Ventura, 14: Sonoma]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: "Install BASH (newer macOS versions use Zsh by default)"
        run: brew install bash

      - name: "Remove Python 3 for Python 3.11 symbolic link"
        shell: bash
        run: brew unlink python@3.11 && brew link --overwrite python@3.11 && brew unlink python@3.10 && brew link --overwrite python@3.10

      - name: "Install Dependencies"
        shell: bash
        run: ./scripts/setup.sh

      - name: "Build AutonomySim"
        shell: bash
        run: ./scripts/build.sh
