---
#----------------------------------------------------------------------------------------
# FILENAME:
#   test_linux.yml
# DESCRIPTION:
#   GitHub Actions configuration for Linux.
# AUTHOR:
#   Adam Erickson (Nervosys)
# DATE:
#   2024-02-20
# NOTES:
#
#   Copyright © 2024 Nervosys, LLC
#----------------------------------------------------------------------------------------

name: "Build: Linux"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]
  # workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }} # ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04] # versions 20, 22
        arch:
          - amd64
          # - arm64
    steps:
      - uses: actions/checkout@v4

      - name: "Install Dependencies"
        shell: bash
        run: bash ./scripts/setup.sh

      - name: "Build AutonomySim"
        shell: bash
        run: bash ./scripts/build.sh

      - name: "Build ROS2 Wrapper"
        # if: ${{ matrix.os == 'ubuntu-20.04' }}
        shell: bash
        run: |
          bash ./scripts/install_ros2_deps.sh
          source /opt/ros/*/setup.bash
          cd ./ros2
          colcon build --cmake-args -DCMAKE_C_COMPILER=gcc-11 --cmake-args -DCMAKE_CXX_COMPILER=g++-11
